testing: true

# Site settings
# Course Info
title: "Advanced Calculus II"
email: "&#x64;&#x6b;&#x72;&#x61;&#x73;&#x68;&#x65;&#x6e;&#x40;&#x75;&#x70;&#x65;&#x6e;&#x6e;&#x2e;&#x65;&#x64;&#x75;"
tagline: "UPenn MATH 3610, Fall 2022."
description: "Advanced Calculus II"
instructor: "Danny Krashen"
instructor-email: "&#x64;&#x6b;&#x72;&#x61;&#x73;&#x68;&#x65;&#x6e;&#x40;&#x75;&#x70;&#x65;&#x6e;&#x6e;&#x2e;&#x65;&#x64;&#x75;"
office: "DRL 3E6"
office-hour: "Thursdays 5:10pm - 6:00pm"

baseurl: "/advancedcalc2"

# url: "localhost:4000"
url: "http://dkrashen.org"

analytics: "true"

# Build settings
markdown: kramdown
permalink: pretty
